import 'dart:convert';

import 'package:shared_preferences/shared_preferences.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

import 'lyrics_service.dart';
import 'word_timing_service.dart';

/// Una riga dei sottotitoli scritti a mano di un video.
class Cue {
  final Duration time;
  final String text;

  const Cue(this.time, this.text);
}

/// Quello che serve per mettere il testo a tempo con il video: la durata
/// vera del video (per scegliere la versione giusta del testo), i
/// sottotitoli scritti a mano e le parole dei sottotitoli automatici, con i
/// loro tempi nel video. Si salva sul telefono.
class VideoSync {
  final int? seconds;
  final List<Cue> cues;
  final List<TimedWord> words;

  const VideoSync(this.seconds, this.cues, this.words);

  static const empty = VideoSync(null, [], []);

  static Future<VideoSync> load(String videoId) async {
    final prefs = await SharedPreferences.getInstance();
    final key = 'sync1:$videoId';
    final cached = prefs.getString(key);
    if (cached != null) return _fromJson(jsonDecode(cached) as Map);
    final sync = await _fetch(videoId);
    // Se non si è letta nemmeno la durata, non salvo: si riprova la volta dopo.
    if (sync.seconds != null) {
      await prefs.setString(key, jsonEncode(_toJson(sync)));
    }
    return sync;
  }

  static Future<VideoSync> _fetch(String videoId) async {
    final yt = YoutubeExplode();
    try {
      final video = await yt.videos.get(videoId);
      final seconds = video.duration?.inSeconds;
      var cues = <Cue>[];
      var words = <TimedWord>[];
      try {
        final manifest = await yt.videos.closedCaptions.getManifest(
          videoId,
          formats: [ClosedCaptionFormat.srv3],
        );
        final english = manifest.tracks.where(
          (t) => t.language.code.startsWith('en'),
        );
        final manual = english.where((t) => !t.isAutoGenerated);
        if (manual.isNotEmpty) {
          final track = await yt.videos.closedCaptions.get(manual.first);
          cues = [
            for (final c in track.captions)
              if (c.text.trim().isNotEmpty) Cue(c.offset, c.text),
          ];
        }
        final auto = english.where((t) => t.isAutoGenerated);
        if (auto.isNotEmpty) {
          final track = await yt.videos.closedCaptions.get(auto.first);
          words = [
            for (final c in track.captions)
              for (final p in c.parts)
                if (p.text.trim().isNotEmpty)
                  TimedWord(p.text.trim(), c.offset + p.offset),
          ];
        }
      } catch (_) {
        // Senza sottotitoli resta la durata.
      }
      return VideoSync(seconds, cues, words);
    } catch (_) {
      return empty;
    } finally {
      yt.close();
    }
  }

  /// Tempi delle righe nel video. Il video può essere spostato rispetto al
  /// testo (un'intro più lunga) o montato in modo diverso (una strofa più
  /// corta): ogni riga ritrovata nei sottotitoli del video prende il suo
  /// tempo vero, le altre seguono lo spostamento dell'ultima ritrovata.
  /// Null se si ritrovano troppo poche righe: allora resta il testo com'è.
  List<Duration>? alignedTimes(List<LyricLine> lines) {
    // Inizio dei sottotitoli: le prime tre parole di ogni riga scritta a
    // mano, oppure ogni terna di parole dei sottotitoli automatici.
    final starts = <String, List<int>>{};
    void add(String text, Duration time) =>
        (starts[text] ??= []).add(time.inMilliseconds);
    if (cues.isNotEmpty) {
      for (final c in cues) {
        final first = _firstWords(c.text);
        if (first != null) add(first, c.time);
      }
    } else {
      final w = [for (final t in words) _norm(t.word)];
      for (var i = 0; i + 2 < w.length; i++) {
        add('${w[i]} ${w[i + 1]} ${w[i + 2]}', words[i].time);
      }
    }
    if (starts.isEmpty) return null;

    int? closest(List<int> times, int target) => times.reduce(
      (a, b) => (a - target).abs() <= (b - target).abs() ? a : b,
    );

    // Spostamento iniziale: il più comune tra le righe (i ritornelli si
    // ripetono, quindi per ogni riga si prende il punto più vicino).
    final diffs = <int>[];
    for (final line in lines) {
      final times = starts[_firstWords(line.english)];
      if (times == null) continue;
      final t = line.time.inMilliseconds;
      final best = closest(times, t)!;
      if ((best - t).abs() <= 60000) diffs.add(best - t);
    }
    if (diffs.length < 5) return null;
    diffs.sort();
    var shift = diffs[diffs.length ~/ 2];

    // Riga per riga, in ordine: si cerca il punto del video vicino a dove
    // dovrebbe stare con lo spostamento attuale, che poi si aggiorna.
    final anchored = List<int?>.filled(lines.length, null);
    for (var i = 0; i < lines.length; i++) {
      final times = starts[_firstWords(lines[i].english)];
      if (times == null) continue;
      final t = lines[i].time.inMilliseconds;
      final best = closest(times, t + shift)!;
      if ((best - (t + shift)).abs() <= 8000) {
        anchored[i] = best;
        shift = best - t;
      }
    }
    if (anchored.whereType<int>().length < 5) return null;

    final firstAnchor = anchored.indexWhere((a) => a != null);
    var current =
        anchored[firstAnchor]! - lines[firstAnchor].time.inMilliseconds;
    final result = <Duration>[];
    for (var i = 0; i < lines.length; i++) {
      final t = lines[i].time.inMilliseconds;
      if (anchored[i] != null) current = anchored[i]! - t;
      var ms = t + current;
      // Mai prima della riga precedente.
      if (result.isNotEmpty && ms < result.last.inMilliseconds) {
        ms = result.last.inMilliseconds;
      }
      result.add(Duration(milliseconds: ms));
    }
    return result;
  }

  static String? _firstWords(String text) {
    final w = _norm(text).split(' ').where((x) => x.isNotEmpty).toList();
    return w.length < 3 ? null : w.take(3).join(' ');
  }

  static String _norm(String s) => s
      .toLowerCase()
      .replaceAll(RegExp(r"[′'’`]"), '')
      .replaceAll(RegExp(r'[^a-z0-9 ]'), ' ')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim();

  static Map<String, dynamic> _toJson(VideoSync s) => {
    'seconds': s.seconds,
    'cues': [
      for (final c in s.cues) [c.time.inMilliseconds, c.text],
    ],
    'words': [
      for (final w in s.words) [w.word, w.time.inMilliseconds],
    ],
  };

  static VideoSync _fromJson(Map j) => VideoSync(
    j['seconds'] as int?,
    [
      for (final c in j['cues'] as List)
        Cue(Duration(milliseconds: c[0] as int), c[1] as String),
    ],
    [
      for (final w in j['words'] as List)
        TimedWord(w[0] as String, Duration(milliseconds: w[1] as int)),
    ],
  );
}
