import 'dart:convert';

import 'package:shared_preferences/shared_preferences.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

/// Una parola dei sottotitoli automatici di YouTube, con il momento in cui
/// viene detta nel video.
class TimedWord {
  final String word;
  final Duration time;

  const TimedWord(this.word, this.time);
}

/// Tempi veri delle parole, presi dai sottotitoli automatici in inglese del
/// video (quando YouTube li ha: non tutte le canzoni li hanno).
class WordTimingService {
  /// Parole con il loro tempo, in ordine; lista vuota se il video non ha
  /// sottotitoli automatici. Il risultato si salva sul telefono.
  static Future<List<TimedWord>> load(String videoId) async {
    final prefs = await SharedPreferences.getInstance();
    final key = 'asr:$videoId';
    final cached = prefs.getString(key);
    if (cached != null) {
      return [
        for (final w in jsonDecode(cached) as List)
          TimedWord(w[0] as String, Duration(milliseconds: w[1] as int)),
      ];
    }
    final words = await _fetch(videoId);
    await prefs.setString(
      key,
      jsonEncode([
        for (final w in words) [w.word, w.time.inMilliseconds],
      ]),
    );
    return words;
  }

  static Future<List<TimedWord>> _fetch(String videoId) async {
    final yt = YoutubeExplode();
    try {
      final manifest = await yt.videos.closedCaptions.getManifest(
        videoId,
        formats: [ClosedCaptionFormat.srv3],
      );
      final auto = manifest.tracks.where(
        (t) => t.isAutoGenerated && t.language.code.startsWith('en'),
      );
      if (auto.isEmpty) return [];
      final track = await yt.videos.closedCaptions.get(auto.first);
      return [
        for (final c in track.captions)
          for (final p in c.parts)
            if (p.text.trim().isNotEmpty)
              TimedWord(p.text.trim(), c.offset + p.offset),
      ];
    } finally {
      yt.close();
    }
  }

  /// Allinea le parole di una riga del testo ai tempi veri di [timed].
  /// Le parole trovate prendono il loro tempo; quelle che il riconoscimento
  /// automatico ha sbagliato si collocano in mezzo alle vicine.
  /// Se nella riga non si trova nessuna parola, resta la stima [estimate].
  static List<Duration> align({
    required List<String> words,
    required Duration lineStart,
    required Duration lineEnd,
    required List<Duration> estimate,
    required List<TimedWord> timed,
  }) {
    final window = [
      for (final t in timed)
        if (t.time >= lineStart - const Duration(seconds: 1) &&
            t.time < lineEnd)
          t,
    ];
    final times = List<Duration?>.filled(words.length, null);
    var next = 0;
    for (var k = 0; k < words.length; k++) {
      final n = _norm(words[k]);
      if (n.isEmpty) continue;
      // Cerco poco più avanti: così una parola sbagliata non fa saltare
      // l'allineamento alla fine della riga.
      for (var x = next; x < window.length && x < next + 4; x++) {
        if (_norm(window[x].word) == n) {
          times[k] = window[x].time;
          next = x + 1;
          break;
        }
      }
    }
    final matched = [
      for (var k = 0; k < words.length; k++)
        if (times[k] != null) k,
    ];
    if (matched.isEmpty) return estimate;

    final first = matched.first;
    final last = matched.last;
    final result = <Duration>[];
    for (var k = 0; k < words.length; k++) {
      final Duration t;
      if (times[k] != null) {
        t = times[k]!;
      } else if (k < first) {
        // Prima della prima parola trovata: tra l'inizio riga e quella.
        t = lineStart + (times[first]! - lineStart) * (k / first);
      } else if (k > last) {
        // Dopo l'ultima trovata: stesso passo della stima.
        t = times[last]! + (estimate[k] - estimate[last]);
      } else {
        final a = matched.lastWhere((m) => m < k);
        final b = matched.firstWhere((m) => m > k);
        t = times[a]! + (times[b]! - times[a]!) * ((k - a) / (b - a));
      }
      // Mai prima della parola precedente.
      result.add(result.isNotEmpty && t < result.last ? result.last : t);
    }
    return result;
  }

  static String _norm(String s) =>
      s.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '');
}
